name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - name: install angular-cli
      run: npm install -g @angular/cli  
    - name: npm build
      run: npm build
    - name: test coverage
      run: ng test --code-coverage
    - name: ng test
      run: ng test
    - name: ng e2e
      run: ng e2e
